env: "local"
photos_path: "./photos/"
database:
  host: localhost
  port: 5432
  name: diplom
  user: postgres
  password: postgres
jwt:
  access_secret: access_secret
  refresh_secret: refresh_secret
  access_expire: 24h
  refresh_expire: 720h
http:
  address: ":8080"